language: node_js
node_js:
  - "10"
install:
  - npm install

  script:
  - npm test
  -npm run coverage


after_script:
   - npm run coverage
   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
